# Ephemeral Pipeline

# This pipeline deploys a blob to a container into a storage account under vnet restriction access

trigger:
- master

resources:
- repo: self

variables:
  ResourceGroup: talksandpocs
  vNetResourceGroup: talksandpocs
  vnetName: vnetworkloadsample
  subnetName: snetagents
  location: westeurope
  acrName: acragentsimages
  imageName: $(acrName).azurecr.io/crossdvlup-agents/ubuntu:latest
  containerName: 'test'
  accountName: 'staworkloadsample'
  agentPoolName: crossdvlup-ubuntu-tf012
  azureSubscription: 'Visual Studio Premium con MSDN'
  containerRegistryConnection: 'acragentsimages'

stages:
- stage: Deploy
  jobs:
  - job: PrepareAgent
    displayName: Prepare Agent
    pool: Hosted Ubuntu 1604
    steps:
    - task: AzureContainerAgentCreate@0
      displayName: 'Azure Container Create for pool crossdvlup-ubuntu-tf012'
      inputs:
        azureSubscription: $(azureSubscription)
        resourceGroupName: $(ResourceGroup)
        location: $(location)
        azureDevOpsToken: $(System.AccessToken)
        containerRegistry: $(containerRegistryConnection)
        imageName: $(imageName)
        agentPool: $(agentPoolName)
        agentPrefix: 'crossdvlup-'
        vnetResourceGroupName: $(vNetResourceGroup)
        vnetName: $(vnetName)
        subnetName: $(subnetName)

  - deployment: Deploy
    environment: 'Production'
    dependsOn: PrepareAgent
    displayName: Deploy Files
    pool: ${{ variables.agentPoolName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: date > $(Pipeline.Workspace)/data.txt
            displayName: 'create dummy file to upload'
          - task: AzureCLI@1
            displayName: 'copy files to container'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptLocation: inlineScript
              inlineScript: |          
                connectionString=$(az storage account show-connection-string --name $(accountName) --query connectionString --output tsv)
                
                echo listing
                az storage blob list --container-name $(containerName) \
                --auth-mode key \
                --connection-string "$connectionString"
                
                echo "uploading"
                
                az storage blob upload-batch --auth-mode key\
                  --account-name $(accountName) \
                  --destination $(containerName) \
                  --source $(Pipeline.Workspace) \
                  --pattern '*.*' \
                  --connection-string "$connectionString"

